#!/bin/bash

# set variables

pipath=pi@169.254.0.2:/home/pi

src="audio.c 
audioFile.c
audioMix.c
audioSample.c
audio.h
behavior.c
behavior.h
config.c
config.h 
control.c 
control.h
device.c
device.h
event.c
event.h
main.c
raspiGPIO.c
raspiGPIO.h
sampler.h"

# make directories

mkdir alsaproj

# fill directories

for i in $src
do
  echo Copying "$i" to alsaproj
  cp "$i" alsaproj
done

cp makefile alsaproj
cp config.txt alsaproj
cp todo.txt alsaproj

# copy to pi

scp -r alsaproj $pipath
